import type { LearningItem } from "./curriculum-types";

/**
 * Fixture Spanish curriculum content, standing in for the real `curriculum`
 * domain (see curriculum-types.ts). Deliberately includes an article-
 * requiring noun, an irregular-article noun, a non-noun with no article, a
 * synonym-bearing item, and a grammar item, so unit/component tests and
 * browser verification can exercise every quiz rule in spec 07 without
 * inventing curriculum data ad hoc elsewhere.
 */
export const FIXTURE_LANGUAGE_ID = "es-MX";

export const FIXTURE_LEARNING_ITEMS: LearningItem[] = [
  {
    type: "vocabulary",
    id: "vocab-gato",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 1,
    word: "gato",
    article: "el",
    partOfSpeech: "noun",
    definition: "A small domesticated feline.",
    meanings: ["cat"],
    targetVariants: [],
    pronunciation: { guide: "GAH-toh", ipa: "ˈɡa.to" },
    context: "Used for domestic cats, as pets or strays.",
    examples: [{ targetText: "El gato duerme.", englishText: "The cat sleeps." }],
    resources: [],
  },
  {
    type: "vocabulary",
    id: "vocab-perro",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 2,
    word: "perro",
    article: "el",
    partOfSpeech: "noun",
    definition: "A domesticated canine.",
    meanings: ["dog"],
    targetVariants: [],
    pronunciation: { guide: "PEH-rroh", ipa: "ˈpe.ro" },
    context: "Used for domestic dogs, as pets or strays.",
    examples: [{ targetText: "El perro corre.", englishText: "The dog runs." }],
    resources: [],
  },
  {
    type: "vocabulary",
    id: "vocab-casa",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 3,
    word: "casa",
    article: "la",
    partOfSpeech: "noun",
    definition: "A building for human habitation.",
    meanings: ["house", "home"],
    targetVariants: [],
    pronunciation: { guide: "KAH-sah", ipa: "ˈka.sa" },
    context: "Refers to a house or, informally, one's home.",
    examples: [{ targetText: "Voy a casa.", englishText: "I'm going home." }],
    resources: [],
  },
  {
    type: "vocabulary",
    id: "vocab-agua",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 4,
    word: "agua",
    // Irregular: feminine noun that takes "el" in the singular to avoid a vowel clash.
    article: "el",
    partOfSpeech: "noun",
    definition: "A clear liquid essential for life.",
    meanings: ["water"],
    targetVariants: [],
    pronunciation: { guide: "AH-gwah", ipa: "ˈa.ɣwa" },
    context: "Takes 'el' rather than 'la' despite being grammatically feminine.",
    examples: [{ targetText: "Bebo agua.", englishText: "I drink water." }],
    creatorNotes: "Irregular article: feminine noun, singular article 'el'.",
    resources: [],
  },
  {
    type: "vocabulary",
    id: "vocab-aprender",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 5,
    word: "aprender",
    partOfSpeech: "verb",
    definition: "To acquire knowledge or a skill.",
    meanings: ["to learn"],
    targetVariants: [],
    pronunciation: { guide: "ah-prehn-DEHR", ipa: "a.pɾenˈdeɾ" },
    context: "A regular -er verb.",
    examples: [{ targetText: "Quiero aprender español.", englishText: "I want to learn Spanish." }],
    resources: [{ label: "-er verb conjugation reference", url: "https://example.com/er-verbs" }],
  },
  {
    type: "vocabulary",
    id: "vocab-comer",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 6,
    word: "comer",
    partOfSpeech: "verb",
    definition: "To consume food.",
    meanings: ["to eat"],
    targetVariants: [],
    pronunciation: { guide: "koh-MEHR", ipa: "koˈmeɾ" },
    context: "A regular -er verb.",
    examples: [{ targetText: "Vamos a comer.", englishText: "Let's go eat." }],
    resources: [],
  },
  {
    type: "grammar",
    id: "grammar-y",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 7,
    structure: "y",
    meaning: "and",
    explanation: "Connects two words, phrases, or clauses.",
    usage: "Standard coordinating conjunction.",
    context: "Becomes 'e' before a word starting with 'i' or 'hi' (not covered at this level).",
    examples: [{ targetText: "gato y perro", englishText: "cat and dog" }],
    resources: [],
    requiredQuestions: [{ format: "translation", direction: "targetToEnglish" }],
  },
  {
    type: "grammar",
    id: "grammar-pero",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 1,
    lessonPriority: 8,
    structure: "pero",
    meaning: "but",
    explanation: "Introduces a contrast between two clauses.",
    usage: "Standard coordinating conjunction.",
    examples: [{ targetText: "Quiero ir, pero no puedo.", englishText: "I want to go, but I can't." }],
    resources: [],
    requiredQuestions: [{ format: "translation", direction: "targetToEnglish" }],
  },
  {
    type: "vocabulary",
    id: "vocab-rojo",
    languageId: FIXTURE_LANGUAGE_ID,
    levelId: 2,
    lessonPriority: 1,
    word: "rojo",
    partOfSpeech: "adjective",
    definition: "The color red.",
    meanings: ["red"],
    targetVariants: [],
    pronunciation: { guide: "ROH-hoh", ipa: "ˈro.xo" },
    context: "Adjectives agree in gender and number; 'rojo' is the masculine singular form.",
    examples: [{ targetText: "El coche es rojo.", englishText: "The car is red." }],
    resources: [],
  },
];
